In [644]:
import time
import pandas as pd
from rake_nltk import Rake
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# column header names for the dataframes
train_col_name = ['userID', 'movieID', 'rating'] #1
tags_col_name=['id','value'] #2
test_col_name=['userID', 'movieID']
movie_tags_col_name=['movieID','tagID','tagWeight'] #3
movie_generes_col_name=['movieID','genre'] #4
movie_directors_col_name=['movieID','directorID','directorName'] #5
movie_actors_col_name=['movieID','actorID','actorName','ranking'] #6
user_taggedmovies_col_name=['userID', 'movieID' ,'tagID'] #7


# reading in data from data files and translating into dataframes
traindf = pd.read_csv('train.dat', sep=' ',skiprows=1,names=train_col_name)
tagsdf=pd.read_csv('tags.dat', sep='\t', skiprows=1,names=tags_col_name, encoding = "ISO-8859-1")
tagsdf.set_index('id', inplace=True) # makes the tagsdf indecies the 'id'

small_testdf=pd.read_csv('small_test.dat', sep=' ',skiprows=1, names=test_col_name)
testdf=pd.read_csv('test.dat', sep=' ',skiprows=1, names=test_col_name)
movie_tagsdf=pd.read_csv('movie_tags.dat', sep='\t',skiprows=1, names=movie_tags_col_name)
movie_generesdf=pd.read_csv('movie_genres.dat', sep='\t',skiprows=1, names=movie_generes_col_name)
movie_actdf=pd.read_csv('movie_actors.dat', sep='\t',skiprows=1,encoding = "ISO-8859-1", names=movie_actors_col_name)
movie_dirdf=pd.read_csv('movie_directors.dat', encoding = "ISO-8859-1",skiprows=1,sep='\t', names=movie_directors_col_name)
user_tmovdf=pd.read_csv('user_taggedmovies.dat', sep=' ', names=user_taggedmovies_col_name)
print("done with reading//")

# print(len(movie_actdf['movieID'].unique()))
# print(len(movie_dirdf['movieID'].unique()))
# print(len(movie_generesdf['movieID'].unique()))

FileNotFoundError: [Errno 2] File b'small_test.dat' does not exist: b'small_test.dat'

In [609]:
# this removes the tags that are used n times or less
movie_tagsdf = movie_tagsdf[movie_tagsdf.tagWeight > 4]
# this removes the actors who have a rating lower than m
movie_actdf = movie_actdf[movie_actdf.ranking > 10]

# ^ removing rows messes with the indices, so here we reset the indices from 0 to n-1
movie_actdf = movie_actdf.reset_index(drop=True)
movie_tagsdf = movie_tagsdf.reset_index(drop=True)
# movie_tagsdf

In [610]:
def movieProfiles():
    newdf=movie_generesdf.groupby('movieID').agg(lambda x:' '.join(x)) #combine generes into single row

    actorsdf1=movie_actdf.drop('ranking',axis=1) #remove columns/features that don't provide additional info.
    actorsdf1=movie_actdf.drop('actorName',axis=1)
    
    actorsdf1=movie_actdf.groupby('movieID').agg(lambda x:' '.join(x)) #combine actors into single row
    movie_dirdf1= \
    movie_dirdf.drop('directorName',axis=1).groupby('movieID').agg(lambda x:' '.join(x)) #combine directors
                                                                                         #and remove column
    arr=[]
    temp=[]
    nextMovieID=1; #start iteration of movie_tagsdf at row 1 because row 0 has column header names
    movie_tags1=movie_tagsdf.drop("tagWeight",axis=1) #removes tagWeight column
    
    for i in range(len(movie_tags1)): # constructing movie tags arrays
        currMovieID = movie_tags1['movieID'][i]
        tagID=movie_tags1['tagID'][i]
        tag=tagsdf['value'][tagID]
        if(currMovieID==nextMovieID):
            temp.append(tag) #add the next tag to the temp array
        else:
            arr.append(temp) #put all the tags we collected in arr position i
            temp=[] #clear them array
            temp.append(tag) #add the next tag to the temp array
            nextMovieID=currMovieID #update the movieID
            
    arr.append(temp)
    
    # converts arrays of tags into strings
    for i in range(len(arr)):
        arr[i]=' '.join(arr[i])
    
    # removes duplicate movie entries and produces a data frame
    ids=movie_tags1['movieID'].unique()
    movie_tags_uniquedf=pd.DataFrame(ids)
    movie_tags_uniquedf['tags']=arr
    movie_tags_uniquedf.columns=["movieID","Movie_tags"]
    
    # we merge on left so that we do not lose any movie due to empty attributes!
    itemProfile=newdf.merge(actorsdf1, how='left',on='movieID')
    itemProfile=itemProfile.merge(movie_dirdf1, how='left',on='movieID')
    itemProfile=itemProfile.merge(movie_tags_uniquedf, how='left',on='movieID')
    
    return itemProfile

In [611]:
# Timer
timeMovieProfile = time.time()
itemProfile = movieProfiles()
print("\tCreating Movie Profiles...\n--- %s seconds ---" % (time.time() - timeMovieProfile))
itemProfile.head()

cell = itemProfile['Movie_tags'][3]
print(f'Empty Cell in row 4 column \'tags\', {cell},is of type:{type(cell)}')

	Creating Movie Profiles...
--- 0.6975657939910889 seconds ---
Empty Cell in row 4 column 'tags', nan,is of type:<class 'float'>

In [612]:
# Timer
timeNan = time.time()
itemProfile = itemProfile.fillna('emptycell')
print("\tReplace NaN float with 'none' str...\n--- %s seconds ---" % (time.time() - timeNan))
itemProfile.head()

cell = itemProfile['Movie_tags'][3]
print(f'Empty Cell in row 4 column \'tags\', cell, is of type:{type(cell)}')

itemProfile

	Replace NaN float with 'none' str...
--- 0.007877111434936523 seconds ---
Empty Cell in row 4 column 'tags', cell, is of type:<class 'str'>

,movieID,genre,actorID,directorID,Movie_tags
0,1,Adventure Animation Children Comedy Fantasy,bill_farmer erik_von_detten greg-berg jan_rabs...,john_lasseter,pixar animation disney toys
1,2,Adventure Children Fantasy,1135379-peter_bryant adam_hannbyrd darryl_henr...,joe_johnston,robin williams
2,3,Comedy Romance,buffy_sedlachek isabell_oconnor john_carroll_l...,donald_petrie,emptycell
3,4,Comedy Drama Romance,1026174-leon brandon-hammond donald_faison ezr...,forest_whitaker,emptycell
4,5,Comedy,ann-walker annie_meyers_shyer april_ortiz bd_w...,charles_shyer,emptycell
5,6,Action Crime Thriller,begonia_plaza bill_mcintosh brian_libby bud_co...,michael_mann,emptycell
6,7,Comedy Romance,1002318-colin_campbell 1050476-paul_harvey bil...,billy_wilder,remake
7,8,Adventure Children,1054869-william_newman 1063598-marian_seldes b...,1052316-peter_hewitt,emptycell
8,9,Action,alan_clement allan_pinsker anthony_marino audr...,peter_hyams,emptycell
9,10,Action Adventure Thriller,billy_mitchell desmond_llewelyn michael_kitche...,martin_campbell,bond
10,11,Comedy Drama Romance,1131202-mark_thompson aaron_sorkin andrew_stee...,rob_reiner,emptycell
11,12,Comedy Horror,alan_walls alton_ruff amy_yesbeck anne_mcvey a...,mel_brooks,emptycell
12,13,Animation Children,1075480-william_roberts brendan_fraser christi...,simon_wells,emptycell
13,14,Drama,1170066-kevin_dunn annabeth_gish bai_ling bori...,oliver_stone,emptycell
14,15,Action Adventure Romance,chris_johnston christopher_kennedy_masterson c...,renny_harlin,emptycell
15,16,Crime Drama,andy_jarrell anthony-russell audrey_meadows bi...,martin_scorsese,mafia martin scorsese
16,17,Comedy Drama Romance,alexander_john elizabeth_spriggs emile_francoi...,ang_lee,emptycell
17,18,Comedy Drama Thriller,1008881-marc_lawrence alicia_witt amanda_de_ca...,alexandre_rockwell,tarantino
18,19,Comedy,adewale_akinnouyeagbaje andrew_steel arsenio_s...,steve_oedekerk,jim carrey
19,20,Action Comedy Crime Drama Thriller,aida_turturro alvaleta_guess bill_nunn christo...,joseph_ruben,emptycell
20,21,Action Comedy Drama,alex_rocco alfred_dennis barry_sonnenfeld bern...,barry_sonnenfeld,emptycell
21,22,Crime Drama Horror Mystery Thriller,anthony_moore arlon_g_greene bert_kinyon bob-g...,jon_amiel,serial killer
22,23,Action Crime Thriller,adriana_altaras anna_sawai david_leitch eleono...,1165744-james_mcteigue,emptycell
23,24,Drama Sci-Fi,alex_allen_morris barry_berfield bill_grant_mi...,victor_salva,emptycell
24,25,Drama Romance,1001899-david_brisbin albert_henderson anne_la...,mike_figgis,emptycell
25,26,Drama,andre_oumansky indra_ove michael_sheen oliver_...,oliver_parker,shakespeare
26,27,Drama,alice_tew beverly_shelton bonnie_hunt bradley_...,lesli_linka_glatter,emptycell
27,28,Drama Romance,darlene_johnson fiona_shaw jane_wood john_wood...,roger_michell,emptycell
28,29,Adventure Drama Fantasy Mystery Sci-Fi,briac_barthelemy cris_huerta francois-hadjilaz...,jeanpierre_jeunet,dystopia surreal
29,30,Crime Drama,yang_qianquan,zhang_yimou,emptycell
...,...,...,...,...,...
10167,64701,Drama Mystery,alain_buron claire_johnston mouss nicole_duboi...,philippe_claudel,emptycell
10168,64716,Drama,andy_milder cynthia_rube gina_hecht ivan_angul...,gabriele_muccino,emptycell
10169,64750,Horror,bruce_ramsay cynthia_preston david-gow helene_...,sandor_stern,emptycell
10170,64839,Drama,ajay_naidu ernest_miller,darren_aronofsky,emptycell
10171,64900,Action Adventure Fantasy Horror Romance,emptycell,ching_siutung,emptycell
10172,64903,Documentary War,emptycell,frank_capra,emptycell
10173,64906,Documentary War,emptycell,frank_capra,emptycell
10174,64918,Drama Romance,emptycell,pascal_bonitzer,emptycell
10175,64921,Action Adventure,emptycell,steve_barron,emptycell
10176,64926,Documentary War,emptycell,frank_capra,emptycell
10177,64930,Comedy Romance,ann_doran ann_savage bob_mckenzie byron_shores...,george_stevens,emptycell
10178,64942,Drama Romance,emptycell,quanan_wang,emptycell
10179,64957,Drama Fantasy Mystery Romance,ed_metzger elle_fanning lance-e-nichols lois_h...,david_fincher,emptycell
10180,64959,Documentary War,emptycell,frank_capra,emptycell
10181,64969,Comedy,brent_briscoe cecilia_antoinette jamie_denbo j...,peyton_reed,emptycell
10182,64976,Comedy,alan_ackles bob-hess cathy_henderson david_sed...,alan-spencer,emptycell
10183,64983,Drama Thriller War,1177389-halina_reijn anton_algrang bernard_hil...,bryan_singer,emptycell
10184,64986,Comedy Drama,emptycell,craig_lucas,emptycell
10185,64990,Documentary,arlo_guthrie bess_lomax_hawes bruce_springstee...,1166349-jim_brown,emptycell
10186,64993,Animation Drama Romance,emptycell,makoto_shinkai,emptycell
10187,64997,Action,daniel_franzese david_alan_basche david_harbou...,steven_spielberg,emptycell
10188,64999,Action,emptycell,c_thomas_howell,emptycell
10189,65006,Mystery Thriller,emptycell,charles_t_kanganis,emptycell
10190,65011,Comedy Drama,emptycell,zdravko_sotra,emptycell
10191,65037,Drama,emptycell,1190387-nic_balthazar,emptycell
10192,65088,Adventure Children Comedy,abigail_leone_droeger adam_shankman aisha_tyle...,adam_shankman,emptycell
10193,65091,Crime Drama Romance,al_thompson alex_melesh bert_russell bert_spro...,ws_van_dyke,emptycell
10194,65126,Comedy Drama,heather-burns isiah_whitlock_jr joel_grey kath...,clark_gregg,emptycell
10195,65130,Drama Romance,max_casella ryan_simpkins ty_simpkins,sam_mendes,emptycell
10196,65133,Comedy,emptycell,paul_weiland,emptycell

In [613]:

def keyWords(columnName):

    for index, row in itemProfile.iterrows():
        feature = row[columnName]

        # instantiating Rake, by default it uses english stopwords from NLTK
        # and discards all puntuation characters as well
        r = Rake()

        # extracting the words by passing the text
        r.extract_keywords_from_text(feature)

        # getting the dictionary whith key words as keys and their scores as values
        key_words_dict_scores = r.get_word_degrees()

        # assigning the key words to the new column for the corresponding movie
        row[columnName] = list(key_words_dict_scores.keys())
#         rowed = row[columnName]
#         if(index < 3):
#     #         print(f'tags = {tags}\n\nkey_words = {list(key_words_dict_scores.keys())}\n----\n')
#             print(f'tags = {feature}\n\nkey_words = {rowed}\n----\n')

In [614]:
timeTags = time.time()
keyWords('Movie_tags')
print("\tCleaning movie tags...\n--- %s seconds ---" % (time.time() - timeTags))

	Cleaning movie tags...
--- 3.632457971572876 seconds ---

In [615]:
timeGenre = time.time()
keyWords('genre')
print("\tCleaning genres...\n--- %s seconds ---" % (time.time() - timeGenre))

	Cleaning genres...
--- 3.6789112091064453 seconds ---

In [616]:
itemProfile.head()

,movieID,genre,actorID,directorID,Movie_tags
0,1,Adventure Animation Children Comedy Fantasy,bill_farmer erik_von_detten greg-berg jan_rabs...,john_lasseter,pixar animation disney toys
1,2,Adventure Children Fantasy,1135379-peter_bryant adam_hannbyrd darryl_henr...,joe_johnston,robin williams
2,3,Comedy Romance,buffy_sedlachek isabell_oconnor john_carroll_l...,donald_petrie,emptycell
3,4,Comedy Drama Romance,1026174-leon brandon-hammond donald_faison ezr...,forest_whitaker,emptycell
4,5,Comedy,ann-walker annie_meyers_shyer april_ortiz bd_w...,charles_shyer,emptycell

In [617]:
#now we join the columns to create our bag of words

itemProfile['Bag'] = itemProfile['genre'].astype(str)+' '+ itemProfile['actorID'] \
                            +' '+itemProfile['directorID']+' '+itemProfile['Movie_tags']
keywordProfile = itemProfile.drop(['genre','actorID','directorID','Movie_tags'],axis=1)
keywordProfile.head()

   movieID                                                Bag
0        1  Adventure Animation Children Comedy Fantasy bi...
1        2  Adventure Children Fantasy 1135379-peter_bryan...
2        3  Comedy Romance buffy_sedlachek isabell_oconnor...
3        4  Comedy Drama Romance 1026174-leon brandon-hamm...
4        5  Comedy ann-walker annie_meyers_shyer april_ort...

In [636]:
# instantiating and generating the count matrix
count = CountVectorizer()
# count = TfidfVectorizer()

timeCount = time.time()
count_matrix = count.fit_transform(keywordProfile['Bag'])
print("\tCreating count matrix...\n--- %s seconds ---" % (time.time() - timeCount))

	Creating count matrix...
--- 0.4170961380004883 seconds ---

In [637]:
# generating the cosine similarity matrix
timeCos_sim = time.time()
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print("\tComputing cosine similarities...\n--- %s seconds ---" % (time.time() - timeCos_sim))

	Computing cosine similarities...
--- 6.162452936172485 seconds ---

In [641]:
# creating a Series for the movie titles so they are associated to an ordered numerical
# list I will use in the function to match the indexes
movieIDs = pd.Series(keywordProfile.movieID)
movieIDs.head()

0    1
1    2
2    3
3    4
4    5
Name: movieID, dtype: int64

In [642]:

# Needed: defining the function that takes in userID and movieID and determines
# the rating the user will give this movie
# Nice if it could: already watched the movie? then we just use the same rating!
def recommendations(userID, movieID, cosine_sim = cosine_sim):

    idx = movieIDs[movieIDs == movieID].index[0] #use iloc to index the keywordProfile with idx!!!
    #idx is the index in keywordProfile!
    sim_movie_arr = cosine_sim[idx]
    watched = traindf[traindf['userID'] == userID]
    watchedIDs = pd.DataFrame(watched.movieID)
    
    #creates a user profile of movies watched and their ratings
    user_sim_dict = {"movieID":[],"similarity":[]}
    for i in range(len(movieIDs)):
        this_movie = movieIDs[i]
        if this_movie in watchedIDs.values:
            user_sim_dict['movieID'].append(this_movie)
            user_sim_dict['similarity'].append(sim_movie_arr[i])
    #sorts user movies by similarity to the new movie
    user_sim_df = pd.DataFrame(user_sim_dict).sort_values('similarity',ascending=False)
    user_sim_df.reset_index(inplace=True)
    
    #averages ratings of top 5 similar movies the user has watched
    rating = 0
    for i in range(5):
        index = user_sim_df['index'][i]
        print(watched['rating'][index])
        rating += watched['rating'][index]
        
    avg_rating = rating/5
    
    return avg_rating

In [643]:
timeRecommend = time.time()
rating = recommendations(75, 1, cosine_sim = cosine_sim)
print("\tCreating count matrix...\n--- %s seconds ---" % (time.time() - timeRecommend))
print(f'user rating = {rating}')

1.5
4.5
3.5
4.5
3.5
	Creating count matrix...
--- 0.27330589294433594 seconds ---
user rating = 3.5

In [ ]:
for